<?xml version="1.0" encoding="utf-8"?><Database Name="Financa_shkolla" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-H41N2OC\SQLEXPRESS;Initial Catalog=MSSql82549;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Financa_shkollaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cmimet" Member="Cmimets">
    
   
    <Type Name="Cmimet">
      <Column Name="Klasa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cmimi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Valuta" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Viti_shkollor" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Prenotimi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Valuta_prenotimi" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Cmimi_trans" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Valuta_trans" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Nxenesi" Member="Nxenesis">
    <Type Name="Nxenesi">
      <Column Name="Id_nxenesi" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nr_amza" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Klasa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Indeksi" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Emri" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Mbiemri" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Atesia" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Memesia" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nr_tel" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Viti_shkollor" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Ditelindja" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Nxenesit_keste" Member="Nxenesit_kestes">
    <Type Name="Nxenesit_keste">
      <Column Name="Id_pagesa" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Id_nxenesi" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nr_kesti" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Shpenzime" Member="Shpenzimes">
    <Type Name="Shpenzime">
      <Column Name="Id_shpenzimi" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Emri" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Monedha" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Koment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Shuma" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Nr_fature" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Id_transaksioni" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Skonto" Member="Skontos">
    <Type Name="Skonto">
      <Column Name="Id_nxenesi" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ulje_1" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="Ulje_2" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="Ulje_3" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="Ulje_4" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="Ulje_5" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="Ulje_6" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="Ulje_7" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="Ulje_8" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="Ulje_9" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="Ulje_10" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="Ulje_11" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="Ulje_12" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="Koment" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Te_tjera" Member="Te_tjeras">
    <Type Name="Te_tjera">
      <Column Name="Id_te_tjera" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Hedhje" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Heqje" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Koment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Id_transaksioni" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Pagesa" Member="Pagesas">
    <Type Name="Pagesa">
      <Column Name="Id_pagesa" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nr_fatura" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Monedha" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Skonto" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Penaliteti" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Totali" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Id_transaksioni" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Nr_kestesh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Koment" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Anulluar" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Transporti" Member="Transportis">
    <Type Name="Transporti">
      <Column Name="Id_nxenesi" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nr_kesti" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Vlera" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Aktiv" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Paguar" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Id_pagesa" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Arka" Member="Arkas">
    <Type Name="Arka">
      <Column Name="Id_transaksioni" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tot_S" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Tot_E" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Tot_L" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Koment" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Vendndodhja" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modifikuar_nga" Type="System.String" DbType="NChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Vlera" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Valuta" Type="System.String" DbType="NChar(3) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Kestet" Member="Kestets">
    <Type Name="Kestet">
      <Column Name="Id_nxenesi" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nr_kesti" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Vlera" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Paguar" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Skonto" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Penaliteti" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Id_pagesa" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Aktiv" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pag_neg" Member="Pag_negs">
    <Type Name="Pag_neg">
      <Column Name="Id_nxenesi" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Vlera" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Prenotimi" Member="Prenotimis">
    <Type Name="Prenotimi">
      <Column Name="Id_nxenesi" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Paguar" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Id_pagesa" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>