#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace financa_shkolla.Account
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Financa_shkolla")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCmimet(Cmimet instance);
    partial void UpdateCmimet(Cmimet instance);
    partial void DeleteCmimet(Cmimet instance);
    partial void InsertNxenesi(Nxenesi instance);
    partial void UpdateNxenesi(Nxenesi instance);
    partial void DeleteNxenesi(Nxenesi instance);
    partial void InsertNxenesit_keste(Nxenesit_keste instance);
    partial void UpdateNxenesit_keste(Nxenesit_keste instance);
    partial void DeleteNxenesit_keste(Nxenesit_keste instance);
    partial void InsertShpenzime(Shpenzime instance);
    partial void UpdateShpenzime(Shpenzime instance);
    partial void DeleteShpenzime(Shpenzime instance);
    partial void InsertSkonto(Skonto instance);
    partial void UpdateSkonto(Skonto instance);
    partial void DeleteSkonto(Skonto instance);
    partial void InsertTe_tjera(Te_tjera instance);
    partial void UpdateTe_tjera(Te_tjera instance);
    partial void DeleteTe_tjera(Te_tjera instance);
    partial void InsertPagesa(Pagesa instance);
    partial void UpdatePagesa(Pagesa instance);
    partial void DeletePagesa(Pagesa instance);
    partial void Insertaspnet_User(aspnet_User instance);
    partial void Updateaspnet_User(aspnet_User instance);
    partial void Deleteaspnet_User(aspnet_User instance);
    partial void InsertTransporti(Transporti instance);
    partial void UpdateTransporti(Transporti instance);
    partial void DeleteTransporti(Transporti instance);
    partial void InsertArka(Arka instance);
    partial void UpdateArka(Arka instance);
    partial void DeleteArka(Arka instance);
    partial void InsertKestet(Kestet instance);
    partial void UpdateKestet(Kestet instance);
    partial void DeleteKestet(Kestet instance);
    partial void InsertPag_neg(Pag_neg instance);
    partial void UpdatePag_neg(Pag_neg instance);
    partial void DeletePag_neg(Pag_neg instance);
    partial void InsertPrenotimi(Prenotimi instance);
    partial void UpdatePrenotimi(Prenotimi instance);
    partial void DeletePrenotimi(Prenotimi instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Financa_shkollaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cmimet> Cmimets
		{
			get
			{
				return this.GetTable<Cmimet>();
			}
		}
		
		public System.Data.Linq.Table<Nxenesi> Nxenesis
		{
			get
			{
				return this.GetTable<Nxenesi>();
			}
		}
		
		public System.Data.Linq.Table<Nxenesit_keste> Nxenesit_kestes
		{
			get
			{
				return this.GetTable<Nxenesit_keste>();
			}
		}
		
		public System.Data.Linq.Table<Shpenzime> Shpenzimes
		{
			get
			{
				return this.GetTable<Shpenzime>();
			}
		}
		
		public System.Data.Linq.Table<Skonto> Skontos
		{
			get
			{
				return this.GetTable<Skonto>();
			}
		}
		
		public System.Data.Linq.Table<Te_tjera> Te_tjeras
		{
			get
			{
				return this.GetTable<Te_tjera>();
			}
		}
		
		public System.Data.Linq.Table<Pagesa> Pagesas
		{
			get
			{
				return this.GetTable<Pagesa>();
			}
		}
		
		public System.Data.Linq.Table<aspnet_User> aspnet_Users
		{
			get
			{
				return this.GetTable<aspnet_User>();
			}
		}
		
		public System.Data.Linq.Table<Transporti> Transportis
		{
			get
			{
				return this.GetTable<Transporti>();
			}
		}
		
		public System.Data.Linq.Table<Arka> Arkas
		{
			get
			{
				return this.GetTable<Arka>();
			}
		}
		
		public System.Data.Linq.Table<Kestet> Kestets
		{
			get
			{
				return this.GetTable<Kestet>();
			}
		}
		
		public System.Data.Linq.Table<Pag_neg> Pag_negs
		{
			get
			{
				return this.GetTable<Pag_neg>();
			}
		}
		
		public System.Data.Linq.Table<Prenotimi> Prenotimis
		{
			get
			{
				return this.GetTable<Prenotimi>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cmimet")]
	public partial class Cmimet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Klasa;
		
		private int _Cmimi;
		
		private string _Valuta;
		
		private string _Viti_shkollor;
		
		private int _Prenotimi;
		
		private string _Valuta_prenotimi;
		
		private decimal _Cmimi_trans;
		
		private string _Valuta_trans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKlasaChanging(int value);
    partial void OnKlasaChanged();
    partial void OnCmimiChanging(int value);
    partial void OnCmimiChanged();
    partial void OnValutaChanging(string value);
    partial void OnValutaChanged();
    partial void OnViti_shkollorChanging(string value);
    partial void OnViti_shkollorChanged();
    partial void OnPrenotimiChanging(int value);
    partial void OnPrenotimiChanged();
    partial void OnValuta_prenotimiChanging(string value);
    partial void OnValuta_prenotimiChanged();
    partial void OnCmimi_transChanging(decimal value);
    partial void OnCmimi_transChanged();
    partial void OnValuta_transChanging(string value);
    partial void OnValuta_transChanged();
    #endregion
		
		public Cmimet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Klasa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Klasa
		{
			get
			{
				return this._Klasa;
			}
			set
			{
				if ((this._Klasa != value))
				{
					this.OnKlasaChanging(value);
					this.SendPropertyChanging();
					this._Klasa = value;
					this.SendPropertyChanged("Klasa");
					this.OnKlasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cmimi", DbType="Int NOT NULL")]
		public int Cmimi
		{
			get
			{
				return this._Cmimi;
			}
			set
			{
				if ((this._Cmimi != value))
				{
					this.OnCmimiChanging(value);
					this.SendPropertyChanging();
					this._Cmimi = value;
					this.SendPropertyChanged("Cmimi");
					this.OnCmimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valuta", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Valuta
		{
			get
			{
				return this._Valuta;
			}
			set
			{
				if ((this._Valuta != value))
				{
					this.OnValutaChanging(value);
					this.SendPropertyChanging();
					this._Valuta = value;
					this.SendPropertyChanged("Valuta");
					this.OnValutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Viti_shkollor", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Viti_shkollor
		{
			get
			{
				return this._Viti_shkollor;
			}
			set
			{
				if ((this._Viti_shkollor != value))
				{
					this.OnViti_shkollorChanging(value);
					this.SendPropertyChanging();
					this._Viti_shkollor = value;
					this.SendPropertyChanged("Viti_shkollor");
					this.OnViti_shkollorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenotimi", DbType="Int NOT NULL")]
		public int Prenotimi
		{
			get
			{
				return this._Prenotimi;
			}
			set
			{
				if ((this._Prenotimi != value))
				{
					this.OnPrenotimiChanging(value);
					this.SendPropertyChanging();
					this._Prenotimi = value;
					this.SendPropertyChanged("Prenotimi");
					this.OnPrenotimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valuta_prenotimi", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Valuta_prenotimi
		{
			get
			{
				return this._Valuta_prenotimi;
			}
			set
			{
				if ((this._Valuta_prenotimi != value))
				{
					this.OnValuta_prenotimiChanging(value);
					this.SendPropertyChanging();
					this._Valuta_prenotimi = value;
					this.SendPropertyChanged("Valuta_prenotimi");
					this.OnValuta_prenotimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cmimi_trans", DbType="Decimal(18,2) NOT NULL")]
		public decimal Cmimi_trans
		{
			get
			{
				return this._Cmimi_trans;
			}
			set
			{
				if ((this._Cmimi_trans != value))
				{
					this.OnCmimi_transChanging(value);
					this.SendPropertyChanging();
					this._Cmimi_trans = value;
					this.SendPropertyChanged("Cmimi_trans");
					this.OnCmimi_transChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valuta_trans", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Valuta_trans
		{
			get
			{
				return this._Valuta_trans;
			}
			set
			{
				if ((this._Valuta_trans != value))
				{
					this.OnValuta_transChanging(value);
					this.SendPropertyChanging();
					this._Valuta_trans = value;
					this.SendPropertyChanged("Valuta_trans");
					this.OnValuta_transChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nxenesi")]
	public partial class Nxenesi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id_nxenesi;
		
		private string _Nr_amza;
		
		private string _Klasa;
		
		private string _Indeksi;
		
		private string _Emri;
		
		private string _Mbiemri;
		
		private string _Atesia;
		
		private string _Memesia;
		
		private string _Nr_tel;
		
		private string _Viti_shkollor;
		
		private string _Ditelindja;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_nxenesiChanging(long value);
    partial void OnId_nxenesiChanged();
    partial void OnNr_amzaChanging(string value);
    partial void OnNr_amzaChanged();
    partial void OnKlasaChanging(string value);
    partial void OnKlasaChanged();
    partial void OnIndeksiChanging(string value);
    partial void OnIndeksiChanged();
    partial void OnEmriChanging(string value);
    partial void OnEmriChanged();
    partial void OnMbiemriChanging(string value);
    partial void OnMbiemriChanged();
    partial void OnAtesiaChanging(string value);
    partial void OnAtesiaChanged();
    partial void OnMemesiaChanging(string value);
    partial void OnMemesiaChanged();
    partial void OnNr_telChanging(string value);
    partial void OnNr_telChanged();
    partial void OnViti_shkollorChanging(string value);
    partial void OnViti_shkollorChanged();
    partial void OnDitelindjaChanging(string value);
    partial void OnDitelindjaChanged();
    #endregion
		
		public Nxenesi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_nxenesi", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id_nxenesi
		{
			get
			{
				return this._Id_nxenesi;
			}
			set
			{
				if ((this._Id_nxenesi != value))
				{
					this.OnId_nxenesiChanging(value);
					this.SendPropertyChanging();
					this._Id_nxenesi = value;
					this.SendPropertyChanged("Id_nxenesi");
					this.OnId_nxenesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_amza", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nr_amza
		{
			get
			{
				return this._Nr_amza;
			}
			set
			{
				if ((this._Nr_amza != value))
				{
					this.OnNr_amzaChanging(value);
					this.SendPropertyChanging();
					this._Nr_amza = value;
					this.SendPropertyChanged("Nr_amza");
					this.OnNr_amzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Klasa", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Klasa
		{
			get
			{
				return this._Klasa;
			}
			set
			{
				if ((this._Klasa != value))
				{
					this.OnKlasaChanging(value);
					this.SendPropertyChanging();
					this._Klasa = value;
					this.SendPropertyChanged("Klasa");
					this.OnKlasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Indeksi", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Indeksi
		{
			get
			{
				return this._Indeksi;
			}
			set
			{
				if ((this._Indeksi != value))
				{
					this.OnIndeksiChanging(value);
					this.SendPropertyChanging();
					this._Indeksi = value;
					this.SendPropertyChanged("Indeksi");
					this.OnIndeksiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emri", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Emri
		{
			get
			{
				return this._Emri;
			}
			set
			{
				if ((this._Emri != value))
				{
					this.OnEmriChanging(value);
					this.SendPropertyChanging();
					this._Emri = value;
					this.SendPropertyChanged("Emri");
					this.OnEmriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mbiemri", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Mbiemri
		{
			get
			{
				return this._Mbiemri;
			}
			set
			{
				if ((this._Mbiemri != value))
				{
					this.OnMbiemriChanging(value);
					this.SendPropertyChanging();
					this._Mbiemri = value;
					this.SendPropertyChanged("Mbiemri");
					this.OnMbiemriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Atesia", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Atesia
		{
			get
			{
				return this._Atesia;
			}
			set
			{
				if ((this._Atesia != value))
				{
					this.OnAtesiaChanging(value);
					this.SendPropertyChanging();
					this._Atesia = value;
					this.SendPropertyChanged("Atesia");
					this.OnAtesiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Memesia", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Memesia
		{
			get
			{
				return this._Memesia;
			}
			set
			{
				if ((this._Memesia != value))
				{
					this.OnMemesiaChanging(value);
					this.SendPropertyChanging();
					this._Memesia = value;
					this.SendPropertyChanged("Memesia");
					this.OnMemesiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_tel", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nr_tel
		{
			get
			{
				return this._Nr_tel;
			}
			set
			{
				if ((this._Nr_tel != value))
				{
					this.OnNr_telChanging(value);
					this.SendPropertyChanging();
					this._Nr_tel = value;
					this.SendPropertyChanged("Nr_tel");
					this.OnNr_telChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Viti_shkollor", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Viti_shkollor
		{
			get
			{
				return this._Viti_shkollor;
			}
			set
			{
				if ((this._Viti_shkollor != value))
				{
					this.OnViti_shkollorChanging(value);
					this.SendPropertyChanging();
					this._Viti_shkollor = value;
					this.SendPropertyChanged("Viti_shkollor");
					this.OnViti_shkollorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ditelindja", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ditelindja
		{
			get
			{
				return this._Ditelindja;
			}
			set
			{
				if ((this._Ditelindja != value))
				{
					this.OnDitelindjaChanging(value);
					this.SendPropertyChanging();
					this._Ditelindja = value;
					this.SendPropertyChanged("Ditelindja");
					this.OnDitelindjaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nxenesit_keste")]
	public partial class Nxenesit_keste : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id_pagesa;
		
		private long _Id_nxenesi;
		
		private int _Nr_kesti;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_pagesaChanging(long value);
    partial void OnId_pagesaChanged();
    partial void OnId_nxenesiChanging(long value);
    partial void OnId_nxenesiChanged();
    partial void OnNr_kestiChanging(int value);
    partial void OnNr_kestiChanged();
    #endregion
		
		public Nxenesit_keste()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_pagesa", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id_pagesa
		{
			get
			{
				return this._Id_pagesa;
			}
			set
			{
				if ((this._Id_pagesa != value))
				{
					this.OnId_pagesaChanging(value);
					this.SendPropertyChanging();
					this._Id_pagesa = value;
					this.SendPropertyChanged("Id_pagesa");
					this.OnId_pagesaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_nxenesi", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id_nxenesi
		{
			get
			{
				return this._Id_nxenesi;
			}
			set
			{
				if ((this._Id_nxenesi != value))
				{
					this.OnId_nxenesiChanging(value);
					this.SendPropertyChanging();
					this._Id_nxenesi = value;
					this.SendPropertyChanged("Id_nxenesi");
					this.OnId_nxenesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_kesti", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Nr_kesti
		{
			get
			{
				return this._Nr_kesti;
			}
			set
			{
				if ((this._Nr_kesti != value))
				{
					this.OnNr_kestiChanging(value);
					this.SendPropertyChanging();
					this._Nr_kesti = value;
					this.SendPropertyChanged("Nr_kesti");
					this.OnNr_kestiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Shpenzime")]
	public partial class Shpenzime : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id_shpenzimi;
		
		private string _Emri;
		
		private string _Monedha;
		
		private string _Koment;
		
		private decimal _Shuma;
		
		private long _Nr_fature;
		
		private long _Id_transaksioni;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_shpenzimiChanging(long value);
    partial void OnId_shpenzimiChanged();
    partial void OnEmriChanging(string value);
    partial void OnEmriChanged();
    partial void OnMonedhaChanging(string value);
    partial void OnMonedhaChanged();
    partial void OnKomentChanging(string value);
    partial void OnKomentChanged();
    partial void OnShumaChanging(decimal value);
    partial void OnShumaChanged();
    partial void OnNr_fatureChanging(long value);
    partial void OnNr_fatureChanged();
    partial void OnId_transaksioniChanging(long value);
    partial void OnId_transaksioniChanged();
    #endregion
		
		public Shpenzime()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_shpenzimi", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id_shpenzimi
		{
			get
			{
				return this._Id_shpenzimi;
			}
			set
			{
				if ((this._Id_shpenzimi != value))
				{
					this.OnId_shpenzimiChanging(value);
					this.SendPropertyChanging();
					this._Id_shpenzimi = value;
					this.SendPropertyChanged("Id_shpenzimi");
					this.OnId_shpenzimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emri", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Emri
		{
			get
			{
				return this._Emri;
			}
			set
			{
				if ((this._Emri != value))
				{
					this.OnEmriChanging(value);
					this.SendPropertyChanging();
					this._Emri = value;
					this.SendPropertyChanged("Emri");
					this.OnEmriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monedha", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Monedha
		{
			get
			{
				return this._Monedha;
			}
			set
			{
				if ((this._Monedha != value))
				{
					this.OnMonedhaChanging(value);
					this.SendPropertyChanging();
					this._Monedha = value;
					this.SendPropertyChanged("Monedha");
					this.OnMonedhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Koment", DbType="NVarChar(MAX)")]
		public string Koment
		{
			get
			{
				return this._Koment;
			}
			set
			{
				if ((this._Koment != value))
				{
					this.OnKomentChanging(value);
					this.SendPropertyChanging();
					this._Koment = value;
					this.SendPropertyChanged("Koment");
					this.OnKomentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shuma", DbType="Decimal(18,0) NOT NULL")]
		public decimal Shuma
		{
			get
			{
				return this._Shuma;
			}
			set
			{
				if ((this._Shuma != value))
				{
					this.OnShumaChanging(value);
					this.SendPropertyChanging();
					this._Shuma = value;
					this.SendPropertyChanged("Shuma");
					this.OnShumaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_fature", DbType="BigInt NOT NULL")]
		public long Nr_fature
		{
			get
			{
				return this._Nr_fature;
			}
			set
			{
				if ((this._Nr_fature != value))
				{
					this.OnNr_fatureChanging(value);
					this.SendPropertyChanging();
					this._Nr_fature = value;
					this.SendPropertyChanged("Nr_fature");
					this.OnNr_fatureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_transaksioni", DbType="BigInt NOT NULL")]
		public long Id_transaksioni
		{
			get
			{
				return this._Id_transaksioni;
			}
			set
			{
				if ((this._Id_transaksioni != value))
				{
					this.OnId_transaksioniChanging(value);
					this.SendPropertyChanging();
					this._Id_transaksioni = value;
					this.SendPropertyChanged("Id_transaksioni");
					this.OnId_transaksioniChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Skonto")]
	public partial class Skonto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id_nxenesi;
		
		private System.Nullable<decimal> _Ulje_1;
		
		private System.Nullable<decimal> _Ulje_2;
		
		private System.Nullable<decimal> _Ulje_3;
		
		private System.Nullable<decimal> _Ulje_4;
		
		private System.Nullable<decimal> _Ulje_5;
		
		private System.Nullable<decimal> _Ulje_6;
		
		private System.Nullable<decimal> _Ulje_7;
		
		private System.Nullable<decimal> _Ulje_8;
		
		private System.Nullable<decimal> _Ulje_9;
		
		private System.Nullable<decimal> _Ulje_10;
		
		private System.Nullable<decimal> _Ulje_11;
		
		private System.Nullable<decimal> _Ulje_12;
		
		private string _Koment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_nxenesiChanging(long value);
    partial void OnId_nxenesiChanged();
    partial void OnUlje_1Changing(System.Nullable<decimal> value);
    partial void OnUlje_1Changed();
    partial void OnUlje_2Changing(System.Nullable<decimal> value);
    partial void OnUlje_2Changed();
    partial void OnUlje_3Changing(System.Nullable<decimal> value);
    partial void OnUlje_3Changed();
    partial void OnUlje_4Changing(System.Nullable<decimal> value);
    partial void OnUlje_4Changed();
    partial void OnUlje_5Changing(System.Nullable<decimal> value);
    partial void OnUlje_5Changed();
    partial void OnUlje_6Changing(System.Nullable<decimal> value);
    partial void OnUlje_6Changed();
    partial void OnUlje_7Changing(System.Nullable<decimal> value);
    partial void OnUlje_7Changed();
    partial void OnUlje_8Changing(System.Nullable<decimal> value);
    partial void OnUlje_8Changed();
    partial void OnUlje_9Changing(System.Nullable<decimal> value);
    partial void OnUlje_9Changed();
    partial void OnUlje_10Changing(System.Nullable<decimal> value);
    partial void OnUlje_10Changed();
    partial void OnUlje_11Changing(System.Nullable<decimal> value);
    partial void OnUlje_11Changed();
    partial void OnUlje_12Changing(System.Nullable<decimal> value);
    partial void OnUlje_12Changed();
    partial void OnKomentChanging(string value);
    partial void OnKomentChanged();
    #endregion
		
		public Skonto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_nxenesi", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id_nxenesi
		{
			get
			{
				return this._Id_nxenesi;
			}
			set
			{
				if ((this._Id_nxenesi != value))
				{
					this.OnId_nxenesiChanging(value);
					this.SendPropertyChanging();
					this._Id_nxenesi = value;
					this.SendPropertyChanged("Id_nxenesi");
					this.OnId_nxenesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulje_1", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Ulje_1
		{
			get
			{
				return this._Ulje_1;
			}
			set
			{
				if ((this._Ulje_1 != value))
				{
					this.OnUlje_1Changing(value);
					this.SendPropertyChanging();
					this._Ulje_1 = value;
					this.SendPropertyChanged("Ulje_1");
					this.OnUlje_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulje_2", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Ulje_2
		{
			get
			{
				return this._Ulje_2;
			}
			set
			{
				if ((this._Ulje_2 != value))
				{
					this.OnUlje_2Changing(value);
					this.SendPropertyChanging();
					this._Ulje_2 = value;
					this.SendPropertyChanged("Ulje_2");
					this.OnUlje_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulje_3", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Ulje_3
		{
			get
			{
				return this._Ulje_3;
			}
			set
			{
				if ((this._Ulje_3 != value))
				{
					this.OnUlje_3Changing(value);
					this.SendPropertyChanging();
					this._Ulje_3 = value;
					this.SendPropertyChanged("Ulje_3");
					this.OnUlje_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulje_4", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Ulje_4
		{
			get
			{
				return this._Ulje_4;
			}
			set
			{
				if ((this._Ulje_4 != value))
				{
					this.OnUlje_4Changing(value);
					this.SendPropertyChanging();
					this._Ulje_4 = value;
					this.SendPropertyChanged("Ulje_4");
					this.OnUlje_4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulje_5", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Ulje_5
		{
			get
			{
				return this._Ulje_5;
			}
			set
			{
				if ((this._Ulje_5 != value))
				{
					this.OnUlje_5Changing(value);
					this.SendPropertyChanging();
					this._Ulje_5 = value;
					this.SendPropertyChanged("Ulje_5");
					this.OnUlje_5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulje_6", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Ulje_6
		{
			get
			{
				return this._Ulje_6;
			}
			set
			{
				if ((this._Ulje_6 != value))
				{
					this.OnUlje_6Changing(value);
					this.SendPropertyChanging();
					this._Ulje_6 = value;
					this.SendPropertyChanged("Ulje_6");
					this.OnUlje_6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulje_7", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Ulje_7
		{
			get
			{
				return this._Ulje_7;
			}
			set
			{
				if ((this._Ulje_7 != value))
				{
					this.OnUlje_7Changing(value);
					this.SendPropertyChanging();
					this._Ulje_7 = value;
					this.SendPropertyChanged("Ulje_7");
					this.OnUlje_7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulje_8", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Ulje_8
		{
			get
			{
				return this._Ulje_8;
			}
			set
			{
				if ((this._Ulje_8 != value))
				{
					this.OnUlje_8Changing(value);
					this.SendPropertyChanging();
					this._Ulje_8 = value;
					this.SendPropertyChanged("Ulje_8");
					this.OnUlje_8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulje_9", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Ulje_9
		{
			get
			{
				return this._Ulje_9;
			}
			set
			{
				if ((this._Ulje_9 != value))
				{
					this.OnUlje_9Changing(value);
					this.SendPropertyChanging();
					this._Ulje_9 = value;
					this.SendPropertyChanged("Ulje_9");
					this.OnUlje_9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulje_10", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Ulje_10
		{
			get
			{
				return this._Ulje_10;
			}
			set
			{
				if ((this._Ulje_10 != value))
				{
					this.OnUlje_10Changing(value);
					this.SendPropertyChanging();
					this._Ulje_10 = value;
					this.SendPropertyChanged("Ulje_10");
					this.OnUlje_10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulje_11", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Ulje_11
		{
			get
			{
				return this._Ulje_11;
			}
			set
			{
				if ((this._Ulje_11 != value))
				{
					this.OnUlje_11Changing(value);
					this.SendPropertyChanging();
					this._Ulje_11 = value;
					this.SendPropertyChanged("Ulje_11");
					this.OnUlje_11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulje_12", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Ulje_12
		{
			get
			{
				return this._Ulje_12;
			}
			set
			{
				if ((this._Ulje_12 != value))
				{
					this.OnUlje_12Changing(value);
					this.SendPropertyChanging();
					this._Ulje_12 = value;
					this.SendPropertyChanged("Ulje_12");
					this.OnUlje_12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Koment", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Koment
		{
			get
			{
				return this._Koment;
			}
			set
			{
				if ((this._Koment != value))
				{
					this.OnKomentChanging(value);
					this.SendPropertyChanging();
					this._Koment = value;
					this.SendPropertyChanged("Koment");
					this.OnKomentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Te_tjera")]
	public partial class Te_tjera : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id_te_tjera;
		
		private System.Nullable<decimal> _Hedhje;
		
		private System.Nullable<decimal> _Heqje;
		
		private string _Koment;
		
		private long _Id_transaksioni;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_te_tjeraChanging(long value);
    partial void OnId_te_tjeraChanged();
    partial void OnHedhjeChanging(System.Nullable<decimal> value);
    partial void OnHedhjeChanged();
    partial void OnHeqjeChanging(System.Nullable<decimal> value);
    partial void OnHeqjeChanged();
    partial void OnKomentChanging(string value);
    partial void OnKomentChanged();
    partial void OnId_transaksioniChanging(long value);
    partial void OnId_transaksioniChanged();
    #endregion
		
		public Te_tjera()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_te_tjera", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id_te_tjera
		{
			get
			{
				return this._Id_te_tjera;
			}
			set
			{
				if ((this._Id_te_tjera != value))
				{
					this.OnId_te_tjeraChanging(value);
					this.SendPropertyChanging();
					this._Id_te_tjera = value;
					this.SendPropertyChanged("Id_te_tjera");
					this.OnId_te_tjeraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hedhje", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Hedhje
		{
			get
			{
				return this._Hedhje;
			}
			set
			{
				if ((this._Hedhje != value))
				{
					this.OnHedhjeChanging(value);
					this.SendPropertyChanging();
					this._Hedhje = value;
					this.SendPropertyChanged("Hedhje");
					this.OnHedhjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heqje", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Heqje
		{
			get
			{
				return this._Heqje;
			}
			set
			{
				if ((this._Heqje != value))
				{
					this.OnHeqjeChanging(value);
					this.SendPropertyChanging();
					this._Heqje = value;
					this.SendPropertyChanged("Heqje");
					this.OnHeqjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Koment", DbType="NVarChar(MAX)")]
		public string Koment
		{
			get
			{
				return this._Koment;
			}
			set
			{
				if ((this._Koment != value))
				{
					this.OnKomentChanging(value);
					this.SendPropertyChanging();
					this._Koment = value;
					this.SendPropertyChanged("Koment");
					this.OnKomentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_transaksioni", DbType="BigInt NOT NULL")]
		public long Id_transaksioni
		{
			get
			{
				return this._Id_transaksioni;
			}
			set
			{
				if ((this._Id_transaksioni != value))
				{
					this.OnId_transaksioniChanging(value);
					this.SendPropertyChanging();
					this._Id_transaksioni = value;
					this.SendPropertyChanged("Id_transaksioni");
					this.OnId_transaksioniChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pagesa")]
	public partial class Pagesa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id_pagesa;
		
		private long _Nr_fatura;
		
		private System.DateTime _Data;
		
		private string _Monedha;
		
		private System.Nullable<decimal> _Skonto;
		
		private System.Nullable<decimal> _Penaliteti;
		
		private decimal _Totali;
		
		private long _Id_transaksioni;
		
		private int _Nr_kestesh;
		
		private string _Koment;
		
		private bool _Anulluar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_pagesaChanging(long value);
    partial void OnId_pagesaChanged();
    partial void OnNr_faturaChanging(long value);
    partial void OnNr_faturaChanged();
    partial void OnDataChanging(System.DateTime value);
    partial void OnDataChanged();
    partial void OnMonedhaChanging(string value);
    partial void OnMonedhaChanged();
    partial void OnSkontoChanging(System.Nullable<decimal> value);
    partial void OnSkontoChanged();
    partial void OnPenalitetiChanging(System.Nullable<decimal> value);
    partial void OnPenalitetiChanged();
    partial void OnTotaliChanging(decimal value);
    partial void OnTotaliChanged();
    partial void OnId_transaksioniChanging(long value);
    partial void OnId_transaksioniChanged();
    partial void OnNr_kesteshChanging(int value);
    partial void OnNr_kesteshChanged();
    partial void OnKomentChanging(string value);
    partial void OnKomentChanged();
    partial void OnAnulluarChanging(bool value);
    partial void OnAnulluarChanged();
    #endregion
		
		public Pagesa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_pagesa", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id_pagesa
		{
			get
			{
				return this._Id_pagesa;
			}
			set
			{
				if ((this._Id_pagesa != value))
				{
					this.OnId_pagesaChanging(value);
					this.SendPropertyChanging();
					this._Id_pagesa = value;
					this.SendPropertyChanged("Id_pagesa");
					this.OnId_pagesaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_fatura", DbType="BigInt NOT NULL")]
		public long Nr_fatura
		{
			get
			{
				return this._Nr_fatura;
			}
			set
			{
				if ((this._Nr_fatura != value))
				{
					this.OnNr_faturaChanging(value);
					this.SendPropertyChanging();
					this._Nr_fatura = value;
					this.SendPropertyChanged("Nr_fatura");
					this.OnNr_faturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="DateTime NOT NULL")]
		public System.DateTime Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monedha", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Monedha
		{
			get
			{
				return this._Monedha;
			}
			set
			{
				if ((this._Monedha != value))
				{
					this.OnMonedhaChanging(value);
					this.SendPropertyChanging();
					this._Monedha = value;
					this.SendPropertyChanged("Monedha");
					this.OnMonedhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skonto", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Skonto
		{
			get
			{
				return this._Skonto;
			}
			set
			{
				if ((this._Skonto != value))
				{
					this.OnSkontoChanging(value);
					this.SendPropertyChanging();
					this._Skonto = value;
					this.SendPropertyChanged("Skonto");
					this.OnSkontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Penaliteti", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Penaliteti
		{
			get
			{
				return this._Penaliteti;
			}
			set
			{
				if ((this._Penaliteti != value))
				{
					this.OnPenalitetiChanging(value);
					this.SendPropertyChanging();
					this._Penaliteti = value;
					this.SendPropertyChanged("Penaliteti");
					this.OnPenalitetiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Totali", DbType="Decimal(18,0) NOT NULL")]
		public decimal Totali
		{
			get
			{
				return this._Totali;
			}
			set
			{
				if ((this._Totali != value))
				{
					this.OnTotaliChanging(value);
					this.SendPropertyChanging();
					this._Totali = value;
					this.SendPropertyChanged("Totali");
					this.OnTotaliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_transaksioni", DbType="BigInt NOT NULL")]
		public long Id_transaksioni
		{
			get
			{
				return this._Id_transaksioni;
			}
			set
			{
				if ((this._Id_transaksioni != value))
				{
					this.OnId_transaksioniChanging(value);
					this.SendPropertyChanging();
					this._Id_transaksioni = value;
					this.SendPropertyChanged("Id_transaksioni");
					this.OnId_transaksioniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_kestesh", DbType="Int NOT NULL")]
		public int Nr_kestesh
		{
			get
			{
				return this._Nr_kestesh;
			}
			set
			{
				if ((this._Nr_kestesh != value))
				{
					this.OnNr_kesteshChanging(value);
					this.SendPropertyChanging();
					this._Nr_kestesh = value;
					this.SendPropertyChanged("Nr_kestesh");
					this.OnNr_kesteshChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Koment", DbType="NChar(10)")]
		public string Koment
		{
			get
			{
				return this._Koment;
			}
			set
			{
				if ((this._Koment != value))
				{
					this.OnKomentChanging(value);
					this.SendPropertyChanging();
					this._Koment = value;
					this.SendPropertyChanged("Koment");
					this.OnKomentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anulluar", DbType="Bit NOT NULL")]
		public bool Anulluar
		{
			get
			{
				return this._Anulluar;
			}
			set
			{
				if ((this._Anulluar != value))
				{
					this.OnAnulluarChanging(value);
					this.SendPropertyChanging();
					this._Anulluar = value;
					this.SendPropertyChanged("Anulluar");
					this.OnAnulluarChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.aspnet_Users")]
	public partial class aspnet_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ApplicationId;
		
		private System.Guid _UserId;
		
		private string _UserName;
		
		private string _LoweredUserName;
		
		private string _MobileAlias;
		
		private bool _IsAnonymous;
		
		private System.DateTime _LastActivityDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApplicationIdChanging(System.Guid value);
    partial void OnApplicationIdChanged();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnLoweredUserNameChanging(string value);
    partial void OnLoweredUserNameChanged();
    partial void OnMobileAliasChanging(string value);
    partial void OnMobileAliasChanged();
    partial void OnIsAnonymousChanging(bool value);
    partial void OnIsAnonymousChanged();
    partial void OnLastActivityDateChanging(System.DateTime value);
    partial void OnLastActivityDateChanged();
    #endregion
		
		public aspnet_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ApplicationId
		{
			get
			{
				return this._ApplicationId;
			}
			set
			{
				if ((this._ApplicationId != value))
				{
					this.OnApplicationIdChanging(value);
					this.SendPropertyChanging();
					this._ApplicationId = value;
					this.SendPropertyChanged("ApplicationId");
					this.OnApplicationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoweredUserName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string LoweredUserName
		{
			get
			{
				return this._LoweredUserName;
			}
			set
			{
				if ((this._LoweredUserName != value))
				{
					this.OnLoweredUserNameChanging(value);
					this.SendPropertyChanging();
					this._LoweredUserName = value;
					this.SendPropertyChanged("LoweredUserName");
					this.OnLoweredUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileAlias", DbType="NVarChar(16)")]
		public string MobileAlias
		{
			get
			{
				return this._MobileAlias;
			}
			set
			{
				if ((this._MobileAlias != value))
				{
					this.OnMobileAliasChanging(value);
					this.SendPropertyChanging();
					this._MobileAlias = value;
					this.SendPropertyChanged("MobileAlias");
					this.OnMobileAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAnonymous", DbType="Bit NOT NULL")]
		public bool IsAnonymous
		{
			get
			{
				return this._IsAnonymous;
			}
			set
			{
				if ((this._IsAnonymous != value))
				{
					this.OnIsAnonymousChanging(value);
					this.SendPropertyChanging();
					this._IsAnonymous = value;
					this.SendPropertyChanged("IsAnonymous");
					this.OnIsAnonymousChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActivityDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastActivityDate
		{
			get
			{
				return this._LastActivityDate;
			}
			set
			{
				if ((this._LastActivityDate != value))
				{
					this.OnLastActivityDateChanging(value);
					this.SendPropertyChanging();
					this._LastActivityDate = value;
					this.SendPropertyChanged("LastActivityDate");
					this.OnLastActivityDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transporti")]
	public partial class Transporti : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id_nxenesi;
		
		private int _Nr_kesti;
		
		private decimal _Vlera;
		
		private bool _Aktiv;
		
		private bool _Paguar;
		
		private long _Id_pagesa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_nxenesiChanging(long value);
    partial void OnId_nxenesiChanged();
    partial void OnNr_kestiChanging(int value);
    partial void OnNr_kestiChanged();
    partial void OnVleraChanging(decimal value);
    partial void OnVleraChanged();
    partial void OnAktivChanging(bool value);
    partial void OnAktivChanged();
    partial void OnPaguarChanging(bool value);
    partial void OnPaguarChanged();
    partial void OnId_pagesaChanging(long value);
    partial void OnId_pagesaChanged();
    #endregion
		
		public Transporti()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_nxenesi", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id_nxenesi
		{
			get
			{
				return this._Id_nxenesi;
			}
			set
			{
				if ((this._Id_nxenesi != value))
				{
					this.OnId_nxenesiChanging(value);
					this.SendPropertyChanging();
					this._Id_nxenesi = value;
					this.SendPropertyChanged("Id_nxenesi");
					this.OnId_nxenesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_kesti", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Nr_kesti
		{
			get
			{
				return this._Nr_kesti;
			}
			set
			{
				if ((this._Nr_kesti != value))
				{
					this.OnNr_kestiChanging(value);
					this.SendPropertyChanging();
					this._Nr_kesti = value;
					this.SendPropertyChanged("Nr_kesti");
					this.OnNr_kestiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vlera", DbType="Decimal(18,2) NOT NULL")]
		public decimal Vlera
		{
			get
			{
				return this._Vlera;
			}
			set
			{
				if ((this._Vlera != value))
				{
					this.OnVleraChanging(value);
					this.SendPropertyChanging();
					this._Vlera = value;
					this.SendPropertyChanged("Vlera");
					this.OnVleraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aktiv", DbType="Bit NOT NULL")]
		public bool Aktiv
		{
			get
			{
				return this._Aktiv;
			}
			set
			{
				if ((this._Aktiv != value))
				{
					this.OnAktivChanging(value);
					this.SendPropertyChanging();
					this._Aktiv = value;
					this.SendPropertyChanged("Aktiv");
					this.OnAktivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paguar", DbType="Bit NOT NULL")]
		public bool Paguar
		{
			get
			{
				return this._Paguar;
			}
			set
			{
				if ((this._Paguar != value))
				{
					this.OnPaguarChanging(value);
					this.SendPropertyChanging();
					this._Paguar = value;
					this.SendPropertyChanged("Paguar");
					this.OnPaguarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_pagesa", DbType="BigInt NOT NULL")]
		public long Id_pagesa
		{
			get
			{
				return this._Id_pagesa;
			}
			set
			{
				if ((this._Id_pagesa != value))
				{
					this.OnId_pagesaChanging(value);
					this.SendPropertyChanging();
					this._Id_pagesa = value;
					this.SendPropertyChanged("Id_pagesa");
					this.OnId_pagesaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Arka")]
	public partial class Arka : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id_transaksioni;
		
		private decimal _Tot_S;
		
		private decimal _Tot_E;
		
		private decimal _Tot_L;
		
		private string _Koment;
		
		private string _Vendndodhja;
		
		private System.DateTime _Data;
		
		private string _Modifikuar_nga;
		
		private decimal _Vlera;
		
		private string _Valuta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_transaksioniChanging(long value);
    partial void OnId_transaksioniChanged();
    partial void OnTot_SChanging(decimal value);
    partial void OnTot_SChanged();
    partial void OnTot_EChanging(decimal value);
    partial void OnTot_EChanged();
    partial void OnTot_LChanging(decimal value);
    partial void OnTot_LChanged();
    partial void OnKomentChanging(string value);
    partial void OnKomentChanged();
    partial void OnVendndodhjaChanging(string value);
    partial void OnVendndodhjaChanged();
    partial void OnDataChanging(System.DateTime value);
    partial void OnDataChanged();
    partial void OnModifikuar_ngaChanging(string value);
    partial void OnModifikuar_ngaChanged();
    partial void OnVleraChanging(decimal value);
    partial void OnVleraChanged();
    partial void OnValutaChanging(string value);
    partial void OnValutaChanged();
    #endregion
		
		public Arka()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_transaksioni", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id_transaksioni
		{
			get
			{
				return this._Id_transaksioni;
			}
			set
			{
				if ((this._Id_transaksioni != value))
				{
					this.OnId_transaksioniChanging(value);
					this.SendPropertyChanging();
					this._Id_transaksioni = value;
					this.SendPropertyChanged("Id_transaksioni");
					this.OnId_transaksioniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tot_S", DbType="Decimal(18,2) NOT NULL")]
		public decimal Tot_S
		{
			get
			{
				return this._Tot_S;
			}
			set
			{
				if ((this._Tot_S != value))
				{
					this.OnTot_SChanging(value);
					this.SendPropertyChanging();
					this._Tot_S = value;
					this.SendPropertyChanged("Tot_S");
					this.OnTot_SChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tot_E", DbType="Decimal(18,2) NOT NULL")]
		public decimal Tot_E
		{
			get
			{
				return this._Tot_E;
			}
			set
			{
				if ((this._Tot_E != value))
				{
					this.OnTot_EChanging(value);
					this.SendPropertyChanging();
					this._Tot_E = value;
					this.SendPropertyChanged("Tot_E");
					this.OnTot_EChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tot_L", DbType="Decimal(18,2) NOT NULL")]
		public decimal Tot_L
		{
			get
			{
				return this._Tot_L;
			}
			set
			{
				if ((this._Tot_L != value))
				{
					this.OnTot_LChanging(value);
					this.SendPropertyChanging();
					this._Tot_L = value;
					this.SendPropertyChanged("Tot_L");
					this.OnTot_LChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Koment", DbType="NVarChar(100)")]
		public string Koment
		{
			get
			{
				return this._Koment;
			}
			set
			{
				if ((this._Koment != value))
				{
					this.OnKomentChanging(value);
					this.SendPropertyChanging();
					this._Koment = value;
					this.SendPropertyChanged("Koment");
					this.OnKomentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vendndodhja", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Vendndodhja
		{
			get
			{
				return this._Vendndodhja;
			}
			set
			{
				if ((this._Vendndodhja != value))
				{
					this.OnVendndodhjaChanging(value);
					this.SendPropertyChanging();
					this._Vendndodhja = value;
					this.SendPropertyChanged("Vendndodhja");
					this.OnVendndodhjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="DateTime NOT NULL")]
		public System.DateTime Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modifikuar_nga", DbType="NChar(15) NOT NULL", CanBeNull=false)]
		public string Modifikuar_nga
		{
			get
			{
				return this._Modifikuar_nga;
			}
			set
			{
				if ((this._Modifikuar_nga != value))
				{
					this.OnModifikuar_ngaChanging(value);
					this.SendPropertyChanging();
					this._Modifikuar_nga = value;
					this.SendPropertyChanged("Modifikuar_nga");
					this.OnModifikuar_ngaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vlera", DbType="Decimal(18,2) NOT NULL")]
		public decimal Vlera
		{
			get
			{
				return this._Vlera;
			}
			set
			{
				if ((this._Vlera != value))
				{
					this.OnVleraChanging(value);
					this.SendPropertyChanging();
					this._Vlera = value;
					this.SendPropertyChanged("Vlera");
					this.OnVleraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valuta", DbType="NChar(3) NOT NULL", CanBeNull=false)]
		public string Valuta
		{
			get
			{
				return this._Valuta;
			}
			set
			{
				if ((this._Valuta != value))
				{
					this.OnValutaChanging(value);
					this.SendPropertyChanging();
					this._Valuta = value;
					this.SendPropertyChanged("Valuta");
					this.OnValutaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kestet")]
	public partial class Kestet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id_nxenesi;
		
		private int _Nr_kesti;
		
		private decimal _Vlera;
		
		private bool _Paguar;
		
		private System.Nullable<decimal> _Skonto;
		
		private System.Nullable<decimal> _Penaliteti;
		
		private long _Id_pagesa;
		
		private System.Nullable<bool> _Aktiv;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_nxenesiChanging(long value);
    partial void OnId_nxenesiChanged();
    partial void OnNr_kestiChanging(int value);
    partial void OnNr_kestiChanged();
    partial void OnVleraChanging(decimal value);
    partial void OnVleraChanged();
    partial void OnPaguarChanging(bool value);
    partial void OnPaguarChanged();
    partial void OnSkontoChanging(System.Nullable<decimal> value);
    partial void OnSkontoChanged();
    partial void OnPenalitetiChanging(System.Nullable<decimal> value);
    partial void OnPenalitetiChanged();
    partial void OnId_pagesaChanging(long value);
    partial void OnId_pagesaChanged();
    partial void OnAktivChanging(System.Nullable<bool> value);
    partial void OnAktivChanged();
    #endregion
		
		public Kestet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_nxenesi", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id_nxenesi
		{
			get
			{
				return this._Id_nxenesi;
			}
			set
			{
				if ((this._Id_nxenesi != value))
				{
					this.OnId_nxenesiChanging(value);
					this.SendPropertyChanging();
					this._Id_nxenesi = value;
					this.SendPropertyChanged("Id_nxenesi");
					this.OnId_nxenesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_kesti", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Nr_kesti
		{
			get
			{
				return this._Nr_kesti;
			}
			set
			{
				if ((this._Nr_kesti != value))
				{
					this.OnNr_kestiChanging(value);
					this.SendPropertyChanging();
					this._Nr_kesti = value;
					this.SendPropertyChanged("Nr_kesti");
					this.OnNr_kestiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vlera", DbType="Decimal(18,2) NOT NULL")]
		public decimal Vlera
		{
			get
			{
				return this._Vlera;
			}
			set
			{
				if ((this._Vlera != value))
				{
					this.OnVleraChanging(value);
					this.SendPropertyChanging();
					this._Vlera = value;
					this.SendPropertyChanged("Vlera");
					this.OnVleraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paguar", DbType="Bit NOT NULL")]
		public bool Paguar
		{
			get
			{
				return this._Paguar;
			}
			set
			{
				if ((this._Paguar != value))
				{
					this.OnPaguarChanging(value);
					this.SendPropertyChanging();
					this._Paguar = value;
					this.SendPropertyChanged("Paguar");
					this.OnPaguarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skonto", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Skonto
		{
			get
			{
				return this._Skonto;
			}
			set
			{
				if ((this._Skonto != value))
				{
					this.OnSkontoChanging(value);
					this.SendPropertyChanging();
					this._Skonto = value;
					this.SendPropertyChanged("Skonto");
					this.OnSkontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Penaliteti", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Penaliteti
		{
			get
			{
				return this._Penaliteti;
			}
			set
			{
				if ((this._Penaliteti != value))
				{
					this.OnPenalitetiChanging(value);
					this.SendPropertyChanging();
					this._Penaliteti = value;
					this.SendPropertyChanged("Penaliteti");
					this.OnPenalitetiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_pagesa", DbType="BigInt NOT NULL")]
		public long Id_pagesa
		{
			get
			{
				return this._Id_pagesa;
			}
			set
			{
				if ((this._Id_pagesa != value))
				{
					this.OnId_pagesaChanging(value);
					this.SendPropertyChanging();
					this._Id_pagesa = value;
					this.SendPropertyChanged("Id_pagesa");
					this.OnId_pagesaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aktiv", DbType="Bit")]
		public System.Nullable<bool> Aktiv
		{
			get
			{
				return this._Aktiv;
			}
			set
			{
				if ((this._Aktiv != value))
				{
					this.OnAktivChanging(value);
					this.SendPropertyChanging();
					this._Aktiv = value;
					this.SendPropertyChanged("Aktiv");
					this.OnAktivChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pag_neg")]
	public partial class Pag_neg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id_nxenesi;
		
		private System.Nullable<decimal> _Vlera;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_nxenesiChanging(long value);
    partial void OnId_nxenesiChanged();
    partial void OnVleraChanging(System.Nullable<decimal> value);
    partial void OnVleraChanged();
    #endregion
		
		public Pag_neg()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_nxenesi", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id_nxenesi
		{
			get
			{
				return this._Id_nxenesi;
			}
			set
			{
				if ((this._Id_nxenesi != value))
				{
					this.OnId_nxenesiChanging(value);
					this.SendPropertyChanging();
					this._Id_nxenesi = value;
					this.SendPropertyChanged("Id_nxenesi");
					this.OnId_nxenesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vlera", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Vlera
		{
			get
			{
				return this._Vlera;
			}
			set
			{
				if ((this._Vlera != value))
				{
					this.OnVleraChanging(value);
					this.SendPropertyChanging();
					this._Vlera = value;
					this.SendPropertyChanged("Vlera");
					this.OnVleraChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prenotimi")]
	public partial class Prenotimi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id_nxenesi;
		
		private bool _Paguar;
		
		private long _Id_pagesa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_nxenesiChanging(long value);
    partial void OnId_nxenesiChanged();
    partial void OnPaguarChanging(bool value);
    partial void OnPaguarChanged();
    partial void OnId_pagesaChanging(long value);
    partial void OnId_pagesaChanged();
    #endregion
		
		public Prenotimi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_nxenesi", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id_nxenesi
		{
			get
			{
				return this._Id_nxenesi;
			}
			set
			{
				if ((this._Id_nxenesi != value))
				{
					this.OnId_nxenesiChanging(value);
					this.SendPropertyChanging();
					this._Id_nxenesi = value;
					this.SendPropertyChanged("Id_nxenesi");
					this.OnId_nxenesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paguar", DbType="Bit NOT NULL")]
		public bool Paguar
		{
			get
			{
				return this._Paguar;
			}
			set
			{
				if ((this._Paguar != value))
				{
					this.OnPaguarChanging(value);
					this.SendPropertyChanging();
					this._Paguar = value;
					this.SendPropertyChanged("Paguar");
					this.OnPaguarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_pagesa", DbType="BigInt NOT NULL")]
		public long Id_pagesa
		{
			get
			{
				return this._Id_pagesa;
			}
			set
			{
				if ((this._Id_pagesa != value))
				{
					this.OnId_pagesaChanging(value);
					this.SendPropertyChanging();
					this._Id_pagesa = value;
					this.SendPropertyChanged("Id_pagesa");
					this.OnId_pagesaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
